# Generated by Django 5.0.6 on 2024-07-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitas', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
