# Generated by Django 5.0.6 on 2024-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitas', '0005_alter_carrito_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
